const Tutors = Object.freeze({
  AUSTIN: 12886079,
  ROSHNI: 12988100,
  SUKWON: 12988228,
  ELISA: 12982252,
  ELLEN: 12987942,
  GREGG: 12988141,
  KEYES: 12988199,
  BECCA: 12988171,
  MARIO: 12988057,
  LIZ: 12988194,
  SAANVI: 12862967,
  SAMOUIL: 12889899,
  VICTORIA: 12988124,
  ELIZABETH: 13031007,
  LORA: 13031029,
  MINA: 13031040,
  JESSICA: 13031057,
  CHRISA: 13031100,
  CHRISD: 13031115,
  RICHARD: 13031150,
  MEG: 13031174,
  BURGUNDY: 13031230,
  KATRINA: 13031244,
  ROBBIE: 13031262,
  ROBERT: 13031285,
  DENNIS: 13031302,
  KAREN: 13031328,
  YUMIN: 13065116,
  STEVEN: 13064524,
  PETER: 13064534, 
  JULIA: 13064529,
  CLAYTON: 13064536
});

const DEFAULT_COURSE_TUTOR_MAP = Object.freeze({
  "French I": [Tutors.AUSTIN],
  "French II": [Tutors.AUSTIN],
  "French III": [Tutors.AUSTIN],
  "French IV": [Tutors.AUSTIN],
  "AP French": [Tutors.AUSTIN],
  "AP AB Calculus": [
    Tutors.DENNIS,
    Tutors.ROBERT,
    Tutors.AUSTIN,
    Tutors.SAMOUIL,
    Tutors.MARIO,
    Tutors.KEYES,
    Tutors.LIZ,
    Tutors.ROSHNI,
  ],
  "AP BC Calculus": [
    Tutors.DENNIS,
    Tutors.ROBERT,
    Tutors.AUSTIN,
    Tutors.SAMOUIL,
    Tutors.MARIO,
    Tutors.KEYES,
    Tutors.ROSHNI,
    Tutors.LIZ,
  ],
  "Calculus I": [
    Tutors.DENNIS,
    Tutors.ROBERT,
    Tutors.AUSTIN,
    Tutors.SAMOUIL,
    Tutors.MARIO,
    Tutors.KEYES,
    Tutors.LIZ,
    Tutors.ROSHNI,
    Tutors.ROBBIE,
  ],
  "Calculus II": [
    Tutors.DENNIS,
    Tutors.ROBERT,
    Tutors.AUSTIN,
    Tutors.SAMOUIL,
    Tutors.MARIO,
    Tutors.KEYES,
    Tutors.LIZ,
    Tutors.ROSHNI,
    Tutors.ROBBIE,
  ],
  "Calculus III/Multivariable Calculus": [
    Tutors.DENNIS,
    Tutors.ROBERT,
    Tutors.AUSTIN,
    Tutors.MARIO,
    Tutors.KEYES,
    Tutors.ROSHNI,
    Tutors.ROBBIE,
  ],
  "Linear Algebra": [
    Tutors.DENNIS,
    Tutors.ROBERT,
    Tutors.AUSTIN,
    Tutors.KEYES,
    Tutors.MARIO,
    Tutors.LIZ,
    Tutors.ROSHNI,
    Tutors.MEG,
  ],
  "Algebra II": [
    Tutors.KAREN,
    Tutors.DENNIS,
    Tutors.ROBERT,
    Tutors.SUKWON,
    Tutors.SAMOUIL,
    Tutors.MARIO,
    Tutors.KEYES,
    Tutors.LIZ,
    Tutors.SAANVI,
    Tutors.ELLEN,
    Tutors.ROSHNI,
    Tutors.ROBBIE,
  ],
  "Algebra I": [
    Tutors.KAREN,
    Tutors.DENNIS,
    Tutors.ROBERT,
    Tutors.SUKWON,
    Tutors.SAMOUIL,
    Tutors.MARIO,
    Tutors.KEYES,
    Tutors.LIZ,
    Tutors.SAANVI,
    Tutors.ELLEN,
    Tutors.ROSHNI,
    Tutors.ROBBIE,
  ],
  "Pre-Algebra": [
    Tutors.DENNIS,
    Tutors.ROBERT,
    Tutors.SUKWON,
    Tutors.SAMOUIL,
    Tutors.MARIO,
    Tutors.KEYES,
    Tutors.LIZ,
    Tutors.SAANVI,
    Tutors.ELLEN,
    Tutors.ROSHNI,
    Tutors.ROBBIE,
  ],
  Geometry: [
    Tutors.DENNIS,
    Tutors.ROBERT,
    Tutors.SUKWON,
    Tutors.MARIO,
    Tutors.SAHANA,
    Tutors.KEYES,
    Tutors.SAMUEL,
    Tutors.LIZ,
    Tutors.SAANVI,
    Tutors.ELLEN,
    Tutors.ROSHNI,
    Tutors.ROBBIE,
  ],
  "Pre-Calculus": [
    Tutors.DENNIS,
    Tutors.ROBERT,
    Tutors.AUSTIN,
    Tutors.SAMOUIL,
    Tutors.MARIO,
    Tutors.KEYES,
    Tutors.LIZ,
    Tutors.ROSHNI,
    Tutors.ROBBIE,
  ],
  "AP Statistics and Probability": [
    Tutors.DENNIS,
    Tutors.MARIO,
    Tutors.KEYES,
    Tutors.VICTORIA,
    Tutors.ROSHNI,
  ],
  "Statistics and Probability": [
    Tutors.KAREN,
    Tutors.DENNIS,
    Tutors.MARIO,
    Tutors.KEYES,
    Tutors.VICTORIA,
    Tutors.AUSTIN,
    Tutors.ROSHNI,
  ],
  Trigonometry: [
    Tutors.DENNIS,
    Tutors.AUSTIN,
    Tutors.SAMOUIL,
    Tutors.MARIO,
    Tutors.KEYES,
    Tutors.LIZ,
  ],
  "Spanish I": [Tutors.ELLEN,  Tutors.MEG],
  "Spanish II": [Tutors.ELLEN, Tutors.MEG],
  "Spanish III": [Tutors.ELLEN, Tutors.MEG],
  "Spanish IV": [Tutors.ELLEN, Tutors.MEG],
  "AP Spanish": [Tutors.ELLEN, ],
  English: [
    Tutors.GREGG,
    Tutors.BECCA,
    Tutors.ELLEN,
    Tutors.MARIO,
    Tutors.JESSICA,
    Tutors.CHRISA,
    Tutors.KATRINA,
    Tutors.YUMIN,
  ],
  "AP Language and Composition": [
    Tutors.GREGG,
    Tutors.MARIO,
    Tutors.SUKWON,
    Tutors.JESSICA,
    Tutors.CHRISD,
    Tutors.KATRINA,
    Tutors.YUMIN,
  ],
  "AP Language and Literature": [
    Tutors.GREGG,
    Tutors.MARIO,
    Tutors.JESSICA,
    Tutors.CHRISD,
    Tutors.KATRINA,
    Tutors.YUMIN,
  ],
  "AP European History": [Tutors.SUKWON],
  "AP US History": [Tutors.SUKWON, Tutors.ROSHNI, Tutors.JESSICA, Tutors.KATRINA],
  "AP World History": [Tutors.SUKWON, Tutors.JESSICA, Tutors.KATRINA],
  Biology: [
    Tutors.KAREN,
    Tutors.DENNIS,
    Tutors.ELISA,
    Tutors.ROSHNI,
    Tutors.MEG,
    Tutors.BURGUNDY,
  ],
  "AP Biology": [
    Tutors.KAREN,
    Tutors.DENNIS,
    Tutors.ELISA,

    Tutors.ROSHNI,
    Tutors.MEG,
    Tutors.BURGUNDY,
  ],
  "AP Chemistry": [
    Tutors.KAREN,
    Tutors.DENNIS,
    Tutors.ELISA,

    Tutors.MARIO,
    Tutors.ROSHNI,
    Tutors.RICHARD,
    Tutors.BURGUNDY,
    Tutors.ROBERT,
  ],
  Chemistry: [
    Tutors.KAREN,
    Tutors.DENNIS,
    Tutors.ELISA,

    Tutors.MARIO,
    Tutors.ROSHNI,
    Tutors.BURGUNDY,
    Tutors.ROBERT,
  ],
  "AP Physics I": [
    Tutors.DENNIS,
    Tutors.ROBERT,
    Tutors.MARIO,
    Tutors.SAMOUIL,
    Tutors.KEYES,
    Tutors.ROSHNI,
    Tutors.ROBBIE,
  ],
  "AP Physics II": [
    Tutors.DENNIS,
    Tutors.MARIO,
    Tutors.SAMOUIL,
    Tutors.KEYES,
    Tutors.ROSHNI,
  ],
  "AP Physics C: Mechanics": [
    Tutors.DENNIS,
    Tutors.MARIO,
    Tutors.SAMOUIL,
    Tutors.KEYES,
    Tutors.ROSHNI,
    Tutors.ROBBIE,
  ],
  "AP Physics C: Electricity and Magnetism": [
    Tutors.DENNIS,
    Tutors.KEYES,
    Tutors.ROSHNI,
  ],
  "Physics - Mechanics": [
    Tutors.DENNIS,
    Tutors.MARIO,
    Tutors.SAMOUIL,
    Tutors.KEYES,
    Tutors.ROBBIE,
  ],
  "Physics - Electricity and Magnetism": [Tutors.DENNIS, Tutors.KEYES],
  "AP Computer Science A": [Tutors.AUSTIN, Tutors.MARIO, Tutors.ROSHNI, Tutors.MEG],
  "AP Computer Science Principles": [Tutors.AUSTIN, Tutors.MARIO, Tutors.ROSHNI, Tutors.MEG],
  "Computer Science": [Tutors.AUSTIN, Tutors.MARIO, Tutors.ROSHNI, Tutors.MEG],
  SAT: [
    Tutors.LIZ,
    Tutors.ROSHNI,
    Tutors.MARIO,
    Tutors.SUKWON,
    Tutors.ELIZABETH,
    Tutors.LORA,
    Tutors.MINA,
    Tutors.JESSICA,
    Tutors.CHRISA,
    Tutors.CHRISD,
    Tutors.RICHARD,
    Tutors.MEG,
    Tutors.BURGUNDY,
    Tutors.YUMIN,
    Tutors.BECCA,
  ],
  ACT: [
    Tutors.MARIO,
    Tutors.SUKWON,
    Tutors.LORA,
    Tutors.JESSICA,
    Tutors.CHRISD,
    Tutors.RICHARD,
  ],
  Philosophy: [Tutors.ROSHNI],
  "AP Macroeconomics": [
    Tutors.ROSHNI,
    Tutors.SUKWON,
    Tutors.VICTORIA,
    Tutors.CHRISD,
  ],
  "AP Microeconomics": [
    Tutors.ROSHNI,
    Tutors.SUKWON,
    Tutors.VICTORIA,
    Tutors.CHRISD,
  ],
  Economics: [Tutors.ROSHNI, Tutors.SUKWON, Tutors.VICTORIA],
});

const appointmentTypeIDs = {
  84350758: 60,
  84357869: 90,
  84357852: 120,
};

const ACUITY_USER_ID = "37177822";
